spring.application.name=ait-deliveri
server.port=${PORT_SERVER}

ait.datasource.jdbc-url=${DB_AIT_JDBC}
ait.datasource.username=${DB_AIT_USR}
ait.datasource.password=${DB_AIT_PASS}
ait.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

app.storage.path=${STORAGE_PATH:/app}